### ISSUE TITLE
Compatibility Datagrip 2021.1

### ISSUE THREAD

**Issue by fuglybeastlearn** [chocolate213/json-formatter#2]
Upgraded Datagrip and the Json Formatter is not compatible with the new version. 
![DatagripVersionNumber](https://user-images.githubusercontent.com/28428619/113685304-652bea80-96c6-11eb-8e39-98b48780be11.jpg)
![JsonFormatterError](https://user-images.githubusercontent.com/28428619/113685308-665d1780-96c6-11eb-99b9-8041b7211a41.jpg)

**Comment by chocolate213** [comment]
> Upgraded Datagrip and the Json Formatter is not compatible with the new version.
> ![DatagripVersionNumber](https://user-images.githubusercontent.com/28428619/113685304-652bea80-96c6-11eb-8e39-98b48780be11.jpg)
> ![JsonFormatterError](https://user-images.githubusercontent.com/28428619/113685308-665d1780-96c6-11eb-99b9-8041b7211a41.jpg)

A new version is being uploaded

**Comment by chocolate213** [comment]
Please update to version 1.4
