### ISSUE TITLE
Научите плагин форматировать сериализованные объекты, как это делает JSON Viewer

### ISSUE THREAD

**Issue by chaevnicher** [chocolate213/json-formatter#3]
I cant deserialize object like
`a: 14: {
  i: 0;O: 8: "DateTime": 3: {
    s: 4: "date";s: 26: "2022-11-17 13:00:00.000000";s: 13: "timezone_type";i: 3;s: 8: "timezone";s: 13: "Europe/Moscow";
  }...`
and have an error: Unrecognized token 'a': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

**Comment by chocolate213** [comment]
Cause the input is not a JSON string, JSON string should be start with `{}` or `[]`, see: https://www.json.org/json-en.html
