### ISSUE TITLE
Thanks!!

### ISSUE THREAD

**Issue by Ekryd** [chocolate213/json-formatter#4]
Hi!

I just wanted to say a big "Thank you" for inspiring me to create a GraphQL formatter plugin.
Was able to get my project up and running quickly thanks to your clear code structure.

Kind regards
/Björn

https://github.com/Ekryd/graphql-formatter

**Comment by chocolate213** [comment]
Hi, @Ekryd !

You're welcome! I'm glad to hear that my code was helpful to you and that it inspired you to create a GraphQL formatter plugin. It's always great to see that my work has a positive impact on others. If you have any questions or need further assistance, please feel free to reach out to me.

**Comment by Ekryd** [comment]
Thanks for those kind words ❤️
Feel free to browse my code as well if you find anything useful. I based my plugin on the IntelliJ plugin template on GitHub, and got some GitHub workflows for releasing for free. I think I will try them out in the next few days in order to create releases directly from GitHub (seems like magic!?).

You have had your plugin on the marketplace for a few years. Do you feel that you need to maintain the plugin a lot? Is there something that should be automated from the start?
One thing that I want to automate myself is merging Dependabot PR's automatically. I got that working for a couple of my Maven plugins and it has really saved me a bunch of hours.
