### ISSUE TITLE
请问为什么需要额外定义一个编辑框来格式化json呢？

### ISSUE THREAD

**Issue by yiippee** [chocolate213/json-formatter#5]
感谢你开发的json format插件，请教一个问题，为什么需要额外定义一个编辑框来格式化json呢？而不是在 IDEA 原有的编辑框中进行原地格式化呢？谢谢。
因为我目前在做一个json校验工具插件（内部使用，有具体的校验规则），但是我不想要在额外的编辑框中进行，而是原地执行，同时标记哪些字段校验失败等。

**Comment by chocolate213** [comment]
因为插件的使用场景是格式化、校验一段JSON文本，而不是一个已经存在的JSON文件。就像你说的如果是一个现成的使用IDEA打开的JSON文件本身就能用快捷键格式化

**Comment by yiippee** [comment]
> 因为插件的使用场景是格式化、校验一段JSON文本，而不是一个已经存在的JSON文件。就像你说的如果是一个现成的使用IDEA打开的JSON文件本身就能用快捷键格式化

感谢回复。再请教一个问题哈，侧边栏展开和收回的事件怎么监听啊？有相关api吗？或者有相关的文档介绍吗？谢谢~

**Comment by chocolate213** [comment]
> > 因为插件的使用场景是格式化、校验一段JSON文本，而不是一个已经存在的JSON文件。就像你说的如果是一个现成的使用IDEA打开的JSON文件本身就能用快捷键格式化
> 
> 感谢回复。再请教一个问题哈，侧边栏展开和收回的事件怎么监听啊？有相关api吗？或者有相关的文档介绍吗？谢谢~

可以看下IDEA官网
